// Auto-generated require map: neural-voice rep counts 1-50 (en-US-AvaNeural),
// peak-normalized to full scale. Regenerate with edge-tts + afconvert if the
// voice changes.

export const COUNT_VOICE_SOURCES: number[] = [
	require('@/src/assets/sounds/voice/count_1.m4a'),
	require('@/src/assets/sounds/voice/count_2.m4a'),
	require('@/src/assets/sounds/voice/count_3.m4a'),
	require('@/src/assets/sounds/voice/count_4.m4a'),
	require('@/src/assets/sounds/voice/count_5.m4a'),
	require('@/src/assets/sounds/voice/count_6.m4a'),
	require('@/src/assets/sounds/voice/count_7.m4a'),
	require('@/src/assets/sounds/voice/count_8.m4a'),
	require('@/src/assets/sounds/voice/count_9.m4a'),
	require('@/src/assets/sounds/voice/count_10.m4a'),
	require('@/src/assets/sounds/voice/count_11.m4a'),
	require('@/src/assets/sounds/voice/count_12.m4a'),
	require('@/src/assets/sounds/voice/count_13.m4a'),
	require('@/src/assets/sounds/voice/count_14.m4a'),
	require('@/src/assets/sounds/voice/count_15.m4a'),
	require('@/src/assets/sounds/voice/count_16.m4a'),
	require('@/src/assets/sounds/voice/count_17.m4a'),
	require('@/src/assets/sounds/voice/count_18.m4a'),
	require('@/src/assets/sounds/voice/count_19.m4a'),
	require('@/src/assets/sounds/voice/count_20.m4a'),
	require('@/src/assets/sounds/voice/count_21.m4a'),
	require('@/src/assets/sounds/voice/count_22.m4a'),
	require('@/src/assets/sounds/voice/count_23.m4a'),
	require('@/src/assets/sounds/voice/count_24.m4a'),
	require('@/src/assets/sounds/voice/count_25.m4a'),
	require('@/src/assets/sounds/voice/count_26.m4a'),
	require('@/src/assets/sounds/voice/count_27.m4a'),
	require('@/src/assets/sounds/voice/count_28.m4a'),
	require('@/src/assets/sounds/voice/count_29.m4a'),
	require('@/src/assets/sounds/voice/count_30.m4a'),
	require('@/src/assets/sounds/voice/count_31.m4a'),
	require('@/src/assets/sounds/voice/count_32.m4a'),
	require('@/src/assets/sounds/voice/count_33.m4a'),
	require('@/src/assets/sounds/voice/count_34.m4a'),
	require('@/src/assets/sounds/voice/count_35.m4a'),
	require('@/src/assets/sounds/voice/count_36.m4a'),
	require('@/src/assets/sounds/voice/count_37.m4a'),
	require('@/src/assets/sounds/voice/count_38.m4a'),
	require('@/src/assets/sounds/voice/count_39.m4a'),
	require('@/src/assets/sounds/voice/count_40.m4a'),
	require('@/src/assets/sounds/voice/count_41.m4a'),
	require('@/src/assets/sounds/voice/count_42.m4a'),
	require('@/src/assets/sounds/voice/count_43.m4a'),
	require('@/src/assets/sounds/voice/count_44.m4a'),
	require('@/src/assets/sounds/voice/count_45.m4a'),
	require('@/src/assets/sounds/voice/count_46.m4a'),
	require('@/src/assets/sounds/voice/count_47.m4a'),
	require('@/src/assets/sounds/voice/count_48.m4a'),
	require('@/src/assets/sounds/voice/count_49.m4a'),
	require('@/src/assets/sounds/voice/count_50.m4a'),
];
